//
//  termsOfService.swift
//  JobsMatch
//
//  Created by ivans Android on 1/9/25.
//

import SwiftUI

struct termsOfService: View {
    @Environment(\.dismiss) private var dismiss
    var body: some View {
        ScrollView{
            VStack(spacing: 3){
                ZStack {
                    // HStack for the dismiss button aligned to the left
                    HStack {
                        Button(action: { dismiss() }) {
                            Image(systemName: "chevron.left")
                                .resizable()
                                .aspectRatio(contentMode: .fit)
                                .frame(width: 22, height: 22)
                                .foregroundColor(.black)
                                .padding()
                        }
                        Spacer() // This pushes the button to the left
                    }
                    // Centered image
                    Image("WaveJustLogoWhite")
                        .resizable()
                        .frame(width: 150, height: 125)
                        .padding(.top)
                    }
                    .padding(.bottom)
                    Spacer()
                    VStack{
                        Text("Mobile Application Terms of Use")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 23))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    VStack(spacing:5){
                        HStack(spacing:-140){
                            Text("Effective Date:")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 15))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("January 1, 2025")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 15))
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .underline()
                        }
                        HStack(spacing:-140){
                            Text("Last Updated:")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 15))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("January 11, 2025")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 15))
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .underline()
                        }
                    }
                    Spacer()
                    Text("Table of Contents")
                        .foregroundStyle(.black)
                        .font(Font.custom("Orkney-Bold", size: 20))
                        .frame(maxWidth: .infinity, alignment: .leading)
                    VStack(alignment:.leading){
                        Text("1. AGREEMENT TO TERMS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. The Company")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("2. PAYMENTS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. Forms of Payment")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("B. Subscriptions")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("I. Cancellation")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("II. Fee Changes")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("III. Free Trials")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("C. Currency")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("D. Refund Policy")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("E. In-App Purchases")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("3. ACCESS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. Minors(Under the age of 18)")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("B. Children(Under the age of 13)")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("4. PROHIBITED ACTIVITIES")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("5. USER-GENERATED CONTENT")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("6. GUIDELINES FOR REVIEWS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("7. MOBILE APPLICATION LICENSE")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. Use License")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("B. Apple and Android Devices")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("8. COPYRIGHT POLICY")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. Intellectual Property Infringement")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("B. DMCA Notice and DMCA Procedure for Copyright Infringement Claims")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("9. INTELLECTUAL PROPERTY")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("10. USER OBLIGATION")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("11. USER ACCOUNTS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("12. SOCIAL MEDIA")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("13. SUBMISSIONS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("14. THIRD(3RD) PARTY WEBSITE AND CONTENT")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("15. SITE MANAGEMENT")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("16. PRIVACY POLICY")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("17. TERMINATION")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("18. GOVERNING LAW")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("19. DISPUTE RESOLUTION")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. Mediation")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("B. Arbitration")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("20. AS IS DISCLAIMER")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("21. INDEMINFICATION")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("22. NOTICES")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("23. USER DATA")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("24. ELECTRONIC  MEANS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("25. CALIFORNIA USERS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("26. EUROPEAN UNION (EU) USERS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("27. UNTIED STATES FEDERAL GOVERNMENT END-USER PROVISIONS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("28. MISCELLANEOUS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.top)
                    .padding(.bottom)
                    dividerWithLabel(label: "Terms of Service")
                        .padding()
                    VStack{
                        Text("1. AGREEMENT TO TERMS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("The Terms of Use Agreement ('Agreement'), created on the effective date and last amended on the date above, is made between you ('user,' 'you,' or 'your') and:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("A. The Company")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 17))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            HStack(spacing:-155){
                                Text("Website URL:")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("www.jobsmatch.io")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                    .underline()
                                    .foregroundColor(.black)
                            }
                            HStack(spacing:-130){
                                Text("Company Name:")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("JobsMatch Inc.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                    .underline()
                                    .foregroundColor(.black)
                            }
                            HStack(spacing:-10){
                                Text("Doing Business as (DBA):")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("NA")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                    .underline()
                                    .foregroundColor(.black)
                            }
                            HStack(spacing:-140){
                                Text("Street Address:")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("1216 Grove Avenue")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                     .frame(maxWidth: .infinity, alignment: .leading)
                                     .underline()
                                     .foregroundColor(.black)
                             }
                             HStack(spacing:-155){
                                 Text("City/State:")
                                     .foregroundStyle(.black)
                                     .font(Font.custom("Orkney-Bold", size: 14))
                                     .frame(maxWidth: .infinity, alignment: .leading)
                                 Text("Burlingame, California")
                                     .foregroundStyle(.black)
                                     .font(Font.custom("Orkney-Bold", size: 14))
                                     .frame(maxWidth: .infinity, alignment: .leading)
                                     .underline()
                                     .foregroundColor(.black)
                             }
                             HStack(spacing:-155){
                                 Text("Zip Code:")
                                     .foregroundStyle(.black)
                                     .font(Font.custom("Orkney-Bold", size: 14))
                                     .frame(maxWidth: .infinity, alignment: .leading)
                                 Text("94010")
                                     .foregroundStyle(.black)
                                     .font(Font.custom("Orkney-Bold", size: 14))
                                     .frame(maxWidth: .infinity, alignment: .leading)
                                     .underline()
                                     .foregroundColor(.black)
                             }
                         }
                         Text("The owner mentioned above includes its affiliated companies, websites, applications, software, and tools (the “Company,” “we,” “us,” or “our”), and, with this Agreement, outlines the rights and obligations that you and all users share, as well as any other media form, media channel, mobile website or mobile application related or connected thereto (collectively, the “website”), for the purpose of making use of any of the content, software, or other tools on the website (“services”).")
                             .foregroundStyle(.black)
                             .font(Font.custom("Orkney-Bold", size: 14))
                     }
                     .padding(.bottom)
                    VStack{
                        Text("2. PAYMENTS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            HStack{
                                Image(systemName:"checkmark.square")
                                Text("Free and accessible by all users.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                Spacer()
                            }
                            HStack{
                                Image(systemName:"square")
                                Text("Paid in accordance with the terms below:")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                Spacer()
                            }
                            Text("A. Forms of Payment")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("We accept payment through the methods offered at the time of purchase or when a balance is due. The provider and method of payment are determined by your location, device, and purchased item. We reserve the right, at any time, to reject payment for any reason.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                            Text("B. Subscriptions")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("If any of the services offered by us are only available with a paid subscription, you will be billed in advance and on a recurring and periodic basis (such as daily, weekly, monthly, annually, or other agreed upon timeframes) at the end of each period. With each successful payment, the subscription will automatically renew under the same conditions unless canceled.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                            VStack{
                                Text("I. Cancellation")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 17))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("You are entitled to cancel a subscription at any time and in accordance with the terms of this Agreement. Cancellation does not entitle you to a refund for any prior payments made.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("II. Fee Changes")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 17))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("If any changes occur to the subscription amount, you will be given notice of at least one (1) billing cycle prior to the change taking effect. Notice will be provided by e-mail on your registered account or profile.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("III. Free Trials")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 17))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("Any free trial, sample, or other abridged versions of our services that are offered shall be considered a one (1) time use based on the registration of a user's e-mail. It is strictly prohibited for a user to create and register more than one (1) e-mail solely to access another free trial on the website")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            .padding(.leading)
                            Text("C. Currency")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("Payments will be accepted on the website in the currency based on your location and in accordance with local laws.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                            Text("D. Refund Policy")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("Except when required by law, payments made by a user are not refundable by the company. Refund requests are administered on a case-by-case basis and, if granted, do so at the sole discretion of the company.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                            Text("E. In-App Purchases")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("If the website’s services are offered on an Android, iOS, or other mobile application (“mobile app”), this Agreement also applies to payments made on the mobile app. In addition, payments made on the mobile app must also be in accordance with the terms of the mobile app platform or “store.”")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                        }
                    }
                    .padding(.bottom)
                    VStack{
                        Text("3. ACCESS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("Your access to and use of the website and the services is conditional upon your acceptance of and compliance with this Agreement, which applies to all the website’s visitors. If, for any reason, you do not agree with any of the terms of this Agreement, you may not access the website or its services. Additionally, your access to and use of the services is conditional upon your acceptance of and compliance with our privacy policy which describes our policies and procedure on the collection, use, and disclosure of your personal information, which is initiated by and commences when you use the website. The privacy policy discloses details and discloses your privacy rights and protections under applicable laws. It is advised to read our privacy policy prior to accessing the website or its services.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                        VStack{
                            Text("A. Minors(Under the age of 18)")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("If any user is a minor in the jurisdiction where they reside, they must obtain permission from their parent or guardian to use the website. If a minor accesses the website, it is assumed that their parent or guardian has read and agrees to this Agreement and has given permission to the minor to use the website.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("B. Children(Under the age of 13)")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("If any user is a child under the age of thirteen (13) years and from the United States, it is assumed that they have obtained permission and verifiable parental consent to use the website. Furthermore, this Agreement allows the protections mentioned under the Children’s Online Privacy Protection, specifically, 15 U.S. Code § 6502.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                        .padding(.bottom)
                        Text("We do not claim that the website's content is appropriate or suitable for you or any visitor. No information, data, or information provided on the website is intended for distribution or use in any location where such usage is prohibited or is contrary to any law or regulation which would subject the Company to legal liability of any type. Any such access or use of the website is to be utilized on your own initiative, and you are solely responsible for any legal compliance. Any supplemental amendments or documents on the website following the effective date of this Agreement are to be considered expressly incorporated into this Agreement.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                    }
                    .padding(.bottom)
                    VStack{
                        Text("4. PROHIBITED ACTIVITIES")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("As a user of our services, whether on the website or mobile app, it is prohibited to engage in the following activities:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("• Systematically retrieve data or other content from the website or services to create or compile, directly or indirectly, a collection, compilation, database, or directory without our written permission;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Trick, defraud, or mislead other users or us, especially in any attempt to learn sensitive account information such as user passwords;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Circumvent, disable, or otherwise interfere with security-related features of thewebsite or services, including those that restrict the copying of content or protected marks;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Disparage, tarnish, or otherwise harm the company, website, mobile app, or any other platforms where the services are offered;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Use any information obtained from the website or the service to harass, abuse, or harm another person or group of people;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Make improper use of our support services, specifically our customer service representatives, or make false reports of abuse or misconduct;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Use the website or services in a manner that is inconsistent with its intended use or against any applicable laws;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Engage in spamming, linking, or referring to other websites for commercial or other purposes;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Upload or transmit, or the attempt of such act, viruses, trojan horses, or other damaging or improper material, including the spamming or continuous posting of repetitive text, that has the potential to interfere, modify, impair, disrupt, alter, or interfere with another user’s experience with the website or its features, functions, operations, or maintenance;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Attempting any unauthorized automated use of the website, such as using scripts to send comments and messages, or using mining tools with the intention of gathering, injecting, or extracting data;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Deleting copyrights, trademarks, disclaimers, or any other marks from the website or its content;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Impersonating another user or person by use of a username, e-mail, personal name, or in any other manner;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Upload or transmit, or the attempt of such act, any material that acts as a passive or active information collection or transmission mechanism, including, without limitation, clear graphics interchange formats ('gifs'), 1x1 pixels, web bugs, cookies, or other similar devices, also known as 'spyware,' 'passive collection mechanisms' or 'PCM';")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Interfering with, disrupting, or creating an undue burden on the website, services, networks, and other connections;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Harassing, annoying, intimidating, or threatening any of the other users, employees, agents, contractors, or any other individual affiliated with the company;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Disabling or attempting to disable restrictions implemented by the website that prohibits access to certain areas;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Copying or adapting the software of the website, including but not limited to Flash, PHP, HTML, JavaScript, or other code;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Deciphering, decompiling, disassembling, or reverse engineering any of the software on the website;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Except as may be the result of a standard search engine or internet browser usage, to use, launch, develop, or distribute any automated system, including, without limitation, any crawlable spider, robot or bots, cheat utility, scraper, or offline reader that accessed the website or services, or using or launching any unauthorized script or other software;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Using a buying or purchasing agent to make purchases on the website;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Making any unauthorized use of the website or the services, such as collecting usernames, e-mail addresses, or personal names of users by electronic or other means to send unsolicited e-mails or create user accounts by automated means or under false pretenses;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Using the website or services as part of any effort to compete with us or otherwise using the website, services, marks, content, data, or any part thereof for any revenue-generating endeavor, commercial purpose, or personal benefit;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Using the website or services to advertise or offer to sell goods or other services; and")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Selling your user profile or account on the website.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                    }
                    .padding(.leading)
                    VStack{
                        Text("5. USER-GENERATED ACCOUNT")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("Our website or services may allow you to chat, make postings (available for public or private viewing), or other communication functionalities, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials on the website, including but not limited to, text, writings, video, audio, photos, graphics, comments, suggestions, personal information or other material (collectively known as the “content”). Content may be viewable by other users or the general public. As such, any content transmitted by you may be treated as non-confidential and non-proprietary. When you create or make any content available on the website, you are accepting that:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("• The creation, distribution, transmission, public display, or performance of displaying your content to be widely available for accessing, downloading, or copying does not infringe your or its proprietary rights, including but not limited to any copyrights, trademarks, patents, trade secrets, confidential information or moral rights of a 3rd party;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• You are the creator and owner of or have the necessary licenses, rights, consent, releases, and permissions to use and to authorize us, and other users of the website, to use your content in any manner deemed reasonable;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• You have the written consent, release, or permission of each and every identifiable individual in your content to use their name or likeness;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content is not false, inaccurate, or misleading to the detriment of other users, the website, or any 3rd party;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content is not unsolicited or unauthorized advertising, used for promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content is not obscene, lewd, lascivious, filthy, violent, considered harassment, libelous, defamatory, or otherwise objectionable (as determined by us);")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content does not ridicule, mock, disparage, intimidate, or verbally abuse other users or us;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content is not used to harass or threaten (in the legal sense of those terms) any user or individual or promotes violence against a specific person or class of people;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content does not violate any applicable laws or regulations;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content does not violate may privacy-related concerns or the publicity rights of any 3rd party;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content does not include offensive comments related to groups of race,national origin, gender, relationship status, familial status, religion, sexual preference, or physical handicap; and")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Your content does not link to material that violates any of the aforementioned provisions of this section or this Agreement.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                        Text("By posting your content on our website, you grant us the right and license to use,modify and publicly perform, display, reproduce, and distribute such content. You retain any and all of your rights to any content you submit, post, or display and are responsible for protecting those rights. This license includes the right for us to make your content available to other users of the website, 3rd parties, and the general public, with or without your consent.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("6. GUIDELINES FOR REVIEWS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("We may provide you, either on the website or by a 3rd party, the right to leave a review or rating of the services offered. Said review or rating requires that you:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("• Should have firsthand experience with the person/entity being reviewed;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not contain any offensive, abusive, racist, profanity-laden language;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not reference discriminatory language or references related to religion, race, gender, national origin, age, marital status, sexual orientation, or disability;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not include references to illegal activity;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not post negative reviews as part of a scheme working with a competitor of ours;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not make any suggestions or conclusions as to the legality of our services, products, or conduct;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not post any false or misleading comments about your experience with the website or our company; and")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Do not organize a campaign encouraging others to post reviews, whether positive or negative.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                        Text("In our sole discretion, we may decide to accept, reject, or remove reviews. Our responsibility is to screen reviews to ensure that any postings regarding the website and its services are accurate and verifiable. Any reviews made by you or other users of the website do not represent our opinions or statements of the services or our affiliates or partners. We do not assume liability, claims, or losses resulting from any review made on the website. By posting a review, you hereby grant us a perpetual, nonexclusive, worldwide, commercial, royalty-free, and assignable license (and sublicense ability) to reproduce, modify, translate, transmit by any means, display, perform, and/or distribute all content relating to such reviews made.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("7. MOBILE APPLICATION LICENSE")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("If a proprietary mobile application is offered in connection to the services offered on the website (“mobile app”), the following will apply:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("A. Use License")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("We grant you a revocable, nonexclusive, non-transferable, and limited license to install and use the mobile app to access the website and its services. Under such license, you agree that it is prohibited to conduct the following:")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            VStack{
                                Text("• Except as permitted by applicable law, to decompile, reverse engineer, disassemble, attempt to derive source code, or decrypt any part of the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Make any modification, adaptation, improvement, enhancement, translation, or derivative work from the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Violate any applicable laws or regulations in connection with your use or access to the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Use the mobile app for any revenue-generating endeavor, commercial enterprise, or other purposes for which it is not designed or intended;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Allow the mobile app to be available over a network or other environment that permits access or use by multiple devices or users at the same time;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Use the mobile app for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Use the mobile app to send automated queries to any other website or application for unsolicited use, commercial or non-commercial; and")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Use any proprietary information provided by or through the use of the mobile app for the design, development, licensure, or distribution of any other applications, accessories, or other devices for use with the mobile app.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            .padding(.leading)
                            Text("B. Apple and Android Devices")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("When using the mobile app on an Apple or Android device (“mobile platform”), the following will apply:")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            VStack{
                                Text("• The license granted to you when using the mobile app is limited to a non-transferable license on a device that utilizes either of the mobile platforms, as applicable, in accordance with the usage rules set forth in the applicable mobile platform’s terms of service and any other applicable documents;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• It is known that we are responsible for providing any maintenance and support services with respect to the mobile app in regard to updates made by the mobile platform and in its day-to-day use;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Any refund requests made by you from purchases made on the mobile app must be requested on the mobile platform in accordance with its refund policy. We cannot, on the website, assist in any refund request for payments made on the mobile app;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• If the jurisdiction or governing law of the company or mobile app is located in the United States, you verify that:")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                VStack{
                                    Text("1. You are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country; or")
                                        .foregroundStyle(.black)
                                        .font(Font.custom("Orkney-Bold", size: 14))
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                    Text("2. You are not listed on any U.S. government list of prohibited or restricted parties;")
                                        .foregroundStyle(.black)
                                        .font(Font.custom("Orkney-Bold", size: 14))
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                }
                                .padding(.leading)
                                Text("• You must comply with applicable 3rd party agreements that are used in combination with your wireless plan, network connection, or any other data service or device agreement; and")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• You acknowledge that the mobile platforms used in connection with the mobile app are 3rd party beneficiaries in regard to this Agreement and that each mobile platform will have the right to enforce its terms and conditions regarding your access and activities when using the mobile app.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            .padding(.leading)
                            
                        }
                        .padding(.leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("8. COPYRIGHT POLICY")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("A. Intellectual Property Infringement.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("It is our duty to respect the intellectual property rights of others. Therefore, it is our policy to respond to any claim that infringes on any trademark, copyright, or other intellectual property protected under law. If you are an owner of any protected intellectual property that you feel is being used without your authorization, you must submit notice to us by any of the contact details mentioned herein and include a detailed description of the alleged infringement. If any request is made, and it is determined that you are not the owner of the intellectual property or do not have the authority to act on the owner’s behalf, you may be held accountable for damages which may also include costs related to attorneys’ fees for such misrepresentation.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("B. DMCA Notice and DMCA Procedure for Copyright Infringement Claims.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 17))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our company with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            VStack{
                                Text("• An electronic or physical signature of the copyright owner or a person authorized to act on behalf of the owner of the copyrighted work;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• A description of the copyrighted work that you claim has been infringed, including the URL(s) where the copyrighted work exists or a copy of the copyrighted work;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• Your contact details, including a personal name, address, phone number, and e-mail address;")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• A statement that the copyright infringement is not authorized and that the request to remove the copyrighted work is in good faith; and")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("• A statement by you, with language that includes “under penalty of perjury,” that the information included in the infringement removal is accurate.")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            .padding(.leading)
                            Text("Upon receipt of a copyright infringement notification, we will take whatever steps are required to remove the copyrighted content from the website or the services.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("9. INTELLECTUAL PROPERTY")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("Except as otherwise indicated, all source coding, databases, functionalities, software, graphic designs, and media of any kind (e.g., audio, video, text, photos, etc.), content, trademarks, service marks, logos, and copyrights are considered to be intellectual and proprietary information ('intellectual property'). Such intellectual information is under our ownership and protected by local, state, national, and international laws and will be defended. No intellectual property is permitted to be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold,licensed, or otherwise exploited for commercial purposes without our express prior written permission.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("10. USER OBLIGATIONS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("You, as a user of the website or any of its services, agree to the following:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("• Any information used for registration purposes, if required, must be submitted in an accurate and completed manner;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• If any information should change regarding your account, you agree to change it in a timely fashion;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• You have the legal capacity to understand, agree with, and comply with this Agreement;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• That you are not considered a minor in the jurisdiction where you reside or are accessing the website or its services;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• That you will not access the website or its services through the use of bots, scripts, or any other use than the traditional manner as is intended; and")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• That you will use the website and its services in an authorized and legal manner in accordance with this Agreement.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                        Text("In regard to any of the information submitted by you, if it should be deemed inaccurate, out of date, or incomplete, we reserve the right to terminate your access to the website or account and any future intended use.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("11. USER ACCOUNTS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("If our website allows the creation of a user account of any type, you agree to be responsible for safeguarding its information, including account data, connected e-mails, passwords, and any other personal information. If you are made aware of any breach or unauthorized use of the account, notify us as soon as possible. Furthermore, you agree not to disclose any password created with any 3rd party other than secured services used to assist with saving passwords on your behalf. If the creation of a username is allowed when making an account, such username must be appropriate for public viewing and not violate any trademark, copyright, or other protected names or marks.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("14. THIRD (3RD) PARTY WEBSITE AND CONTENT.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("Our website or services may contain links to 3rd party websites or services that are not owned or controlled by us. Therefore, we assume no responsibility for the content, privacy policies, terms of use, practices, services, experiences, activities, or any other acts by 3rd parties. You acknowledge that if you are to be re-directed or forwarded to such 3rd party website, you hold us harmless and free of liability for any action that should occur on such websites, which may or may not include damages, losses, or any other claims.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("17. PRIVACY POLICY.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("Your access to and use of our website or services is conditional upon your acceptance of our privacy policy. Our privacy policy describes our rules and procedures on the collection, use, and disclosure of your personal information and details your privacy rights and how the law protects you and such data. It is recommended for all users to read to know their rights.We maintain the right to store certain data that you have transmitted by the use of the website or any of our services. You are solely responsible for the data you transmit and how it relates to any activity you have undertaken when using the website and any of its services. Therefore, you agree that we have no liability to you for any loss, breach, or corruption of any data and hereby waive any right of action against us that may or may not arise from such loss, breach, or corruption.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("19. GOVERNING LAW")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("The laws governing the company’s jurisdiction, mentioned in Section 1(a) of this Agreement, shall govern this Agreement, including your use and access to the website and services. Your use of this website, services, and any mobile app may be subject to other local, state, national, and international laws.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("22. INDEMNIFICATION")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("You agree to defend, indemnify, and hold us harmless, including any of our subsidiaries, agents, or affiliates and our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any 3rd party due to or arising out of the following:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            Text("• Our content;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Use of the website or any of our services;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Not able to use the website or any of our services;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Any breach of this Agreement;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Any beach of representations and warranties set forth in this Agreement;")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Any violation of the rights of a 3rd party, including but not limited to intellectual property rights; and")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                            Text("• Any overt harmful act toward any other user of the website or its services.")
                                .foregroundStyle(.black)
                                .font(Font.custom("Orkney-Bold", size: 14))
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .padding(.leading)
                        Text("Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We agree to use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("24. ELECTRONIC MEANS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("When accessing the website or any of its services, sending e-mails, online forms, esignatures, or any type or kind of electronic records or communication, you consent that all agreements, notices, disclosures, and other communications we provide to you in such manner satisfies any legal requirement that such communication should be in writing. You hereby agree that the use of such electronic means will be regarded as sufficient and be viewed as the same as its physical counterpart. Furthermore, you hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("25. CALIFORNIA USERS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in any of the methods below:")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        VStack{
                            VStack{
                                Text("Mail")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 17))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("1625 North Market Blvd, Suite N 112,")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("Sacramento, California")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("95834")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                            VStack{
                                Text("Telephone")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 17))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("(800) 952-5210")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                Text("(916) 445-1254")
                                    .foregroundStyle(.black)
                                    .font(Font.custom("Orkney-Bold", size: 14))
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                        }
                        .padding(.leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("26. EUROPEAN UNION (EU) USERS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("If you are a European Union (EU) resident, consumer, or user, it is recognized that you are entitled to specific protections on how your personal information is collected. We, in our privacy policy, attempt to be in accordance with such rules and regulations.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)
                    VStack{
                        Text("27. UNITED STATES FEDERAL GOVERNMENT END-USER PROVISIONS")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 20))
                            .frame(maxWidth: .infinity, alignment: .leading)
                        Text("If you are a user acting on behalf of the U.S. federal government, our website and its services are treated as a “commercial item” as defined under 48 C.F.R. § 2.101.")
                            .foregroundStyle(.black)
                            .font(Font.custom("Orkney-Bold", size: 14))
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }
                    .padding(.bottom)

                    
                    
                    
                }
                .padding()
            }
        .navigationBarBackButtonHidden(true)
    }
}

#Preview {
    termsOfService()
}
